#' Render function for @@component_name_snake@@ output
#'
#' @param expr An expression that returns the data to be sent to the output.
#'   The data should be in a format that `serde_wasm_bindgen::from_value`
#'   in your Rust code can deserialize into the `ExpectedDataType`.
#' @param env The environment in which `expr` should be evaluated.
#' @param quoted Is `expr` a quoted expression (with `quote()`)? This is useful
#'   for programmatically generated expressions.
#'
#' @return A Shiny render function suitable for assigning to an output slot.
#' @export
render_@@component_name_snake@@ <- function(expr, env = parent.frame(), quoted = FALSE) {
  # Use Shiny's standard functions to turn the expression into a reactive function
  func <- shiny::exprToFunction(expr, env, quoted)

  # Return a reactive that calls the function
  shiny::reactive({
    # Execute the user-provided expression
    val <- func()

    # --- Optional: Add validation or data transformation here ---
    # Ensure 'val' is in the format expected by the Rust deserializer.
    # For example, if Rust expects a list(value=1, label="text"):
    # if (!is.list(val) || !setequal(names(val), c("value", "label"))) {
    #   stop("Value must be a list with 'value' and 'label' elements.")
    # }
    # Or if Rust expects a simple string:
    # if (!is.character(val) || length(val) != 1) {
    #   stop("Value must be a single character string.")
    # }
    # -----------------------------------------------------------

    # Return the value to be sent to the frontend
    val
  })
}

#' UI function for @@component_name_snake@@ output
#'
#' Creates a container in the UI to display the output generated by
#' `render_@@component_name_snake@@`.
#'
#' @param outputId The ID that connects this UI element to the server logic.
#' @param width The width of the output container (e.g., "100%", "400px").
#' @param height The height of the output container (e.g., "300px", "auto").
#' @param ... Other arguments passed to the container tag function.
#'
#' @return An HTML tag object.
#' @export
@@component_name_snake@@_output <- function(outputId, width = "100%", height = "100%", ...) {
  # Use the attach_pkg_deps function defined in R/attach_dependencies.R
  # to ensure the necessary JS and CSS are loaded.
  attach_pkg_deps(
    # Create a div element that will host the Leptos component.
    # The CSS class should match the one used in the TypeScript binding's `find` method.
    shiny::div(
      id = outputId,
      class = "@@package_name_snake@@-@@component_name_snake@@-container",
      style = sprintf(
        "width: %s; height: %s;",
        shiny::validateCssUnit(width),
        shiny::validateCssUnit(height)
      ),
      # Pass any additional attributes to the div
      ...
    )
  )
}
